# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20171124_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
