# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
