# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0006_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_likes',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='users_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
